---
openapi: 3.0.3
info:
  title: backend API
  version: 1.0.0-SNAPSHOT
paths:
  /api/snapshot:
    post:
      tags:
      - Snapshot Controller
      operationId: createNewSnapshot
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                url:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSnapshotResult'
  /api/snapshot/{ref}:
    get:
      tags:
      - Snapshot Controller
      operationId: getShanpshotInfo
      parameters:
      - name: ref
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Snapshot'
  /api/snapshot/{ref}/annotations-config:
    get:
      tags:
      - Snapshot Controller
      operationId: getSnapshotAnnotationsConfig
      parameters:
      - name: ref
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                format: binary
                type: string
  /api/snapshot/{ref}/annotations-svg:
    get:
      tags:
      - Snapshot Controller
      operationId: getSnapshotAnnotationsSvg
      parameters:
      - name: ref
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            image/svg+xml:
              schema:
                format: binary
                type: string
  /api/snapshot/{ref}/finalize-capture:
    post:
      tags:
      - Snapshot Controller
      operationId: finalizeSnapshotCapture
      parameters:
      - name: ref
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                annotations-config:
                  format: binary
                  type: string
                annotations-svg:
                  format: binary
                  type: string
      responses:
        "201":
          description: Created
components:
  schemas:
    CreateSnapshotResult:
      type: object
      properties:
        ref:
          type: string
        uploadBasicInfoLink:
          type: string
        uploadScreenshotLink:
          type: string
        uploadHarLink:
          type: string
        uploadConsoleLink:
          type: string
        uploadHtmlLink:
          type: string
    Date:
      format: date
      type: string
      example: 2022-03-10
    Snapshot:
      type: object
      properties:
        id:
          format: int64
          type: integer
        ref:
          type: string
        pageTitle:
          type: string
        pageUrl:
          type: string
        title:
          type: string
        description:
          type: string
        hasAnnotations:
          type: boolean
        created:
          $ref: '#/components/schemas/Date'
  securitySchemes:
    SecurityScheme:
      type: http
      description: Authentication
      scheme: basic
